language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=4 COVERAGE=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=4

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  # Install suggested modules in order to maximize test coverage
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "ezyang/htmlpurifier:4.*,silverstripe/cms:^4.0@dev"
  - cd ~/builds/ss

script:
  # Execute tests with no coverage. This is the fastest option.
  - "if [ \"$COVERAGE\" != \"1\" ]; then vendor/bin/phpunit comments/tests/; fi"

  # Execute tests with coverage.
  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover comments/tests/; fi"

after_success:
  - "if [ \"$COVERAGE\" = \"1\" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi"
